export const ROUTER = {
    HOME: "/",
    ADMIN: "/admin",
    ADMIN_ORDER_HISTORY: "/admin/order-history",
    ADMIN_RESTAURANTS: "/admin/restaurants",
    ADMIN_LOGIN: "/admin/login",
    ADMIN_CATEGORY: "/admin/category",
    ADMIN_ORDERS: "/admin/orders",
    ADMIN_HISTORY: "/admin/order-history",
    ADMIN_OFFERS: "/admin/offers",
    ADMIN_PRODUCTS: "/admin/products",
    ABOUT_US:"/about-us",
    RESTAURANTS:"/restaurants",
    HOW_IT_WORKS:"/how-it-works",
    FAQS:"/faqs",
    USER_BASKET: "/user/basket",
    USER_ORDERS: "/user/orders",
    USER_CHECKOUT: "/user/checkout",
    USER_PROFILE: "/user/profile",
    USER_RESTAURANTS: "/restaurants",
    LOGIN:"/login",
    REGISTER: "/register",
  } as const;