import React from "react";
import Layout from "@/components/Admin/Layout";
import RestaurantCard from "@/components/Admin/RestaurantCard";
import SearchBar from "@/components/Admin/SearchBar";
import { RestaurantPostDataType } from "../../../interfaces/index";
import { useQuery } from "react-query";
import { getRestaurant } from "@/services/index";
import { QUERIES } from "../../../constant/Queries";
import { SidebarContextProps } from "../../../interfaces/index";
import { useSidebarContext } from "@/contexts/SidebarContext";
import Image from "next/image";
import Head from "next/head";
import NotFound from "@/public/svgs/405.gif";

const Restaurant: React.FC = () => {
  const { selectedCategory, isAdmin } =
    useSidebarContext() as SidebarContextProps;
  const { data, isLoading, isError } = useQuery(
    QUERIES.Restaurants,
    getRestaurant
  );
  const restaurantsData = data?.data.result.data;


  const filteredData =
    selectedCategory !== "" && selectedCategory !== null
      ? restaurantsData?.filter((restaurant: RestaurantPostDataType) => {
          return restaurant.category_id === selectedCategory;
        })
      : restaurantsData;

  return (
    <>
      {isAdmin ? (
        <>
          <Head>
            <title>Admin | Restaurants</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Layout>
            <div className="px-12 md:px-6 h-screen">
              <SearchBar />
              <div className="flex gap-4 sm:gap-6 justify-around sm:justify-start mx-auto flex-wrap ">
                {filteredData &&
                  filteredData.map((restaurant: RestaurantPostDataType) => (
                    <RestaurantCard
                      key={(restaurant.id ?? "").toString()}
                      id={(restaurant.id ?? "").toString()}
                      restaurant={restaurant}
                    />
                  ))}
              </div>
            </div>
          </Layout>
        </>
      ) : (
        <Image
          alt="NotFound"
          height={1000}
          width={1000}
          className="h-screen w-screen"
          src={NotFound}
        />
      )}
    </>
  );
};

export default Restaurant;
