import React from "react";
import UserAside from "../../../components/Client/UserAside/index";
import MainHeader from "../../../components/Client/MainHeader/index";
import UserBasket from "../../../components/Client/BaskerCards/UserBasket";
import DeleteModal from "@/components/Admin/Modals/DeleteModal";
import { useTranslation } from "next-i18next";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import MainFooter from "@/components/Client/MainFooter";
import Head from "next/head";


const BasketUser = () => {
  const { t } = useTranslation("common");

  return (
    <>
      <Head>
        <title>{t("Your Basket")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader />
      <div className="flex flex-col items-center  md:flex-row md:items-start  md:justify-evenly pt-8 pb-32">
        <UserAside />

        <div className="w-10/12 md:w-[72%] bg-[#F3F4F6] dark:bg-gray-900  ">
          <div>
            <div className="capitalize py-2 px-4">
              <span className="text-[30px] text-[#4F4F4F] dark:text-blue-400 tracking-wider font-bold">
                {t("Your Basket")}
              </span>
            </div>
            <UserBasket />
          </div>
        </div>
      </div>

      <DeleteModal />

      <MainFooter />
    </>
  );
};

export default BasketUser;

export const getServerSideProps: GetServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale as string, ["common"])),
  },
});
