import type { NextPage } from "next";
import Head from "next/head";
import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import MainHeader from "@/components/Client/MainHeader";
import { useTranslation } from "next-i18next";
const Home: NextPage = () => {
  const { t } = useTranslation("common");
  return (
    <>
      <Head>
        <title>Foody</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <MainHeader />
        <div className="bg-[#F3F4F6]  dark:bg-gray-900 sm:mx-[30px] rounded-4"></div>
      </div>
    </>
  );
};

export default Home;
export const getServerSideProps: GetServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale as string, ["common"])),
  },
});
